<?php
/**
 * Section registry: every CI360 section, its editable settings and demo defaults.
 * Generated from the CI360 demo theme's field definitions and data/seed.json.
 * Each entry becomes an Elementor widget (category “CI360 Sections”) and is rendered by ci_s_{id}() in inc/sections.php.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function ci_section_defs() {
	static $defs = null;
	if ( null !== $defs ) {
		return $defs;
	}
	$defs = array(
		'home-hero' => array(
			'title'    => 'Home – Hero',
			'icon'     => 'eicon-banner',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Text' ),
				array( 'type' => 'text', 'key' => 'eyebrow', 'label' => 'Eyebrow', 'default' => 'BLUE-SKY THINKING. BUSINESS-GROUND RESULTS.' ),
				array( 'type' => 'text', 'key' => 'title_1', 'label' => 'Title line 1', 'default' => 'Stories that' ),
				array( 'type' => 'text', 'key' => 'title_2', 'label' => 'Title line 2', 'default' => 'move brands' ),
				array( 'type' => 'text', 'key' => 'title_3', 'label' => 'Title line 3 (accent, underlined)', 'default' => 'forward.' ),
				array( 'type' => 'textarea', 'key' => 'description', 'label' => 'Description', 'default' => 'Strategy, creativity, digital and technology — moving together to make brands impossible to ignore.' ),
				array( 'type' => 'text', 'key' => 'cta', 'label' => 'Button text', 'default' => 'Start a conversation' ),
				array( 'type' => 'text', 'key' => 'cta_link', 'label' => 'Button link', 'default' => '/contact/' ),
				array( 'type' => 'text', 'key' => 'secondary', 'label' => 'Secondary link text', 'default' => 'Explore our work' ),
				array( 'type' => 'text', 'key' => 'secondary_link', 'label' => 'Secondary link', 'default' => '#selected-work' ),
				array( 'type' => 'section', 'label' => 'Collage' ),
				array( 'type' => 'text', 'key' => 'collage_label', 'label' => 'Collage label', 'default' => 'A FULL CIRCLE OF POSSIBILITIES.' ),
				array( 'type' => 'repeater', 'key' => 'collage', 'label' => 'Frames (left, main, right)', 'title_field' => 'caption', 'fields' => array( array( 'type' => 'post', 'key' => 'project', 'label' => 'Project', 'source' => 'ci_project', 'default' => '' ), array( 'type' => 'image', 'key' => 'image', 'label' => 'Image', 'default' => '' ), array( 'type' => 'text', 'key' => 'caption', 'label' => 'Caption', 'default' => '' ) ), 'default' => array( array( 'project' => 'vardan', 'image' => 'vardan-sport.webp', 'caption' => 'VARDAN / MOVEMENT' ), array( 'project' => 'crave-eatables', 'image' => 'crave-family.webp', 'caption' => 'CRAVE / EVERYDAY STORIES' ), array( 'project' => 'station-satcom', 'image' => 'station.webp', 'caption' => 'STATION SATCOM / CONNECTIONS' ) ) ),
				array( 'type' => 'html', 'key' => 'sticker', 'label' => 'Sticker', 'default' => 'MAKE<br>IT MOVE.' ),
				array( 'type' => 'text', 'key' => 'collage_caption', 'label' => 'Collage caption', 'default' => 'STRATEGY × STORY × DESIGN × PERFORMANCE' ),
				array( 'type' => 'text', 'key' => 'collage_badge', 'label' => 'Collage badge', 'default' => '360°' ),
				array( 'type' => 'section', 'label' => 'Bottom bar' ),
				array( 'type' => 'text', 'key' => 'bottom_left', 'label' => 'Bottom left', 'default' => 'AHMEDABAD · DELHI · GREENVILLE' ),
				array( 'type' => 'text', 'key' => 'bottom_right', 'label' => 'Bottom right', 'default' => 'SCROLL TO FIND YOUR NEXT PERSPECTIVE' ),
			),
		),
		'brand-strip' => array(
			'title'    => 'Client Logo Strip',
			'icon'     => 'eicon-carousel-loop',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'label', 'label' => 'Label', 'default' => 'IN GOOD COMPANY' ),
				array( 'type' => 'repeater', 'key' => 'logos', 'label' => 'Logos', 'title_field' => 'alt', 'fields' => array( array( 'type' => 'image', 'key' => 'image', 'label' => 'Logo', 'default' => '' ), array( 'type' => 'text', 'key' => 'alt', 'label' => 'Brand name', 'default' => '' ) ), 'default' => null ),
			),
		),
		'home-work' => array(
			'title'    => 'Home – Selected Work (stacked)',
			'icon'     => 'eicon-posts-grid',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => '01 / SELECTED WORK' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'DIFFERENT BRANDS. CONNECTED THINKING.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Not just seen.<br><em>Felt. Remembered.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'From everyday moments to extraordinary possibilities. A selection of the brands in our world.' ),
				array( 'type' => 'text', 'key' => 'anchor', 'label' => 'Section ID (for #links)', 'default' => 'selected-work' ),
				array( 'type' => 'section', 'label' => 'Projects' ),
				array( 'type' => 'posts', 'key' => 'projects', 'label' => 'Projects (empty = featured positions 1–4)', 'source' => 'ci_project', 'default' => array() ),
				array( 'type' => 'text', 'key' => 'card_link', 'label' => 'Card link text', 'default' => 'Explore the project' ),
				array( 'type' => 'text', 'key' => 'end_text', 'label' => 'Closing line', 'default' => 'A collection of different challenges. One integrated approach.' ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Button (%d = number of projects)', 'default' => 'View all %d projects' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Button link', 'default' => '/work/' ),
			),
		),
		'home-capabilities' => array(
			'title'    => 'Home – Capabilities',
			'icon'     => 'eicon-bullet-list',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => '02 / WHAT WE DO' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'ONE PARTNER. EVERY MARKETING POSSIBILITY.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'A full circle<br>of <em>possibilities.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'Strategy, creativity, digital, technology and performance. Working together, not in silos.' ),
				array( 'type' => 'section', 'label' => 'List' ),
				array( 'type' => 'number', 'key' => 'count', 'label' => 'Number of services listed', 'default' => 8 ),
				array( 'type' => 'text', 'key' => 'all_text', 'label' => 'Link (%d = total services)', 'default' => 'Discover all %d capabilities' ),
				array( 'type' => 'text', 'key' => 'all_link', 'label' => 'All services link', 'default' => '/services/' ),
				array( 'type' => 'text', 'key' => 'preview', 'label' => 'Preview caption (first service)', 'default' => 'One clear story. A world of ways to tell it.' ),
			),
		),
		'home-about' => array(
			'title'    => 'Home – About Teaser',
			'icon'     => 'eicon-image-box',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Photo' ),
				array( 'type' => 'image', 'key' => 'image', 'label' => 'Photo', 'default' => 'studio.webp' ),
				array( 'type' => 'html', 'key' => 'stamp', 'label' => 'Photo stamp', 'default' => 'CURIOUS MINDS<br>AT WORK.' ),
				array( 'type' => 'section', 'label' => 'Text' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => '03 / THE AGENCY' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'ALWAYS LOOKING CLOSER' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Big on ideas.<br><em>Closer to you.</em>' ),
				array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Text (blank line between paragraphs)', 'default' => 'CI360 Degrees is an integrated digital marketing and strategic communication agency helping businesses transform ideas into impactful brand experiences and measurable growth.

We begin by listening. Then bring the right minds, disciplines and stories together around your business.' ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Button', 'default' => 'Meet CI360' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Button link', 'default' => '/about/' ),
			),
		),
		'word-marquee' => array(
			'title'    => 'Word Marquee',
			'icon'     => 'eicon-animation-text',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'words', 'label' => 'Marquee words (separate with |)', 'default' => 'LISTEN. | CREATE. | CONNECT. | GROW.' ),
			),
		),
		'process' => array(
			'title'    => 'Process Steps',
			'icon'     => 'eicon-number-field',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'THE PROCESS' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'FROM FIRST QUESTION TO NEXT CHAPTER' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'One story.<br><em>Connected thinking.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'We begin with the business challenge, not the marketing channel.' ),
				array( 'type' => 'section', 'label' => 'Steps' ),
				array( 'type' => 'repeater', 'key' => 'steps', 'label' => 'Steps', 'title_field' => 'title', 'fields' => array( array( 'type' => 'text', 'key' => 'title', 'label' => 'Title', 'default' => '' ), array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Text', 'default' => '' ) ), 'default' => array( array( 'title' => 'Listen', 'text' => 'Every successful partnership begins with listening. We take the time to understand your business, your audience, and your aspirations to uncover what makes your brand unique.' ), array( 'title' => 'Strategic Storytelling', 'text' => 'We transform insights into a compelling brand narrative that shapes every communication, strengthens identity, and creates meaningful audience connections.' ), array( 'title' => 'Create & Execute', 'text' => 'From branding and websites to content, social media, SEO, AEO, and performance marketing, we bring the story to life through integrated marketing solutions.' ), array( 'title' => 'Optimize', 'text' => 'We continuously refine campaigns, content, and digital experiences to maximize engagement, improve performance, and enhance customer experiences.' ), array( 'title' => 'Analytics', 'text' => 'We track performance, measure outcomes, and turn data-driven insights into smarter decisions that fuel continuous growth.' ) ) ),
			),
		),
		'testimonials' => array(
			'title'    => 'Testimonials Slider',
			'icon'     => 'eicon-testimonial-carousel',
			'desc'     => 'Quotes come from Testimonials.',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'KIND WORDS' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'PARTNERSHIPS THAT SPEAK' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Good work.<br><em>Better together.</em>' ),
				array( 'type' => 'number', 'key' => 'count', 'label' => 'Number of testimonials (0 = all)', 'default' => 0 ),
			),
		),
		'insights-teaser' => array(
			'title'    => 'Insights – Latest (with heading)',
			'icon'     => 'eicon-post-list',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => '04 / INSIGHTS' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'THOUGHTS THAT MOVE THE CONVERSATION' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'A fresh<br><em>perspective.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'Marketing never stops evolving, and neither does our thinking. Explore CI360 perspectives on strategic storytelling, digital marketing trends, AI in marketing, SEO, AEO, GEO, performance marketing, brand strategy, content marketing, podcasting, and changing consumer behaviour.' ),
				array( 'type' => 'section', 'label' => 'Posts' ),
				array( 'type' => 'number', 'key' => 'count', 'label' => 'Number of insights', 'default' => 3 ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Button', 'default' => 'Explore our thinking' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Button link', 'default' => '/insights/' ),
			),
		),
		'insights-featured' => array(
			'title'    => 'Insights – Featured + Stack (with carousel)',
			'icon'     => 'eicon-posts-masonry',
			'desc'     => 'Big featured article, three stacked cards, a swipe carousel on mobile and a bottom call to action. Choose where the articles come from under “Articles”.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'select', 'key' => 'style', 'label' => 'Colour style', 'default' => 'dark', 'options' => array( 'dark' => 'Dark (deep navy with glow)', 'light' => 'Light (page background)' ) ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => '04 / INSIGHTS' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'THOUGHTS THAT MOVE THE CONVERSATION' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Insights and<br><em>resources.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'Marketing never stops evolving, and neither does our thinking. Explore CI360 perspectives on strategic storytelling, digital marketing trends, AI in marketing, SEO, AEO, GEO, performance marketing, brand strategy, content marketing, podcasting, and changing consumer behaviour.' ),
				array( 'type' => 'text', 'key' => 'view_text', 'label' => 'View-all button', 'default' => 'View all insights' ),
				array( 'type' => 'text', 'key' => 'view_link', 'label' => 'View-all link', 'default' => '/blogs/' ),
				array( 'type' => 'section', 'label' => 'Articles' ),
				array( 'type' => 'select', 'key' => 'source', 'label' => 'Articles come from', 'default' => 'manual', 'options' => array( 'manual' => 'Chosen below (manual)', 'posts' => 'Latest blog posts', 'insights' => 'CI360 Insights' ) ),
				array( 'type' => 'number', 'key' => 'count', 'label' => 'Number of articles (blog posts / Insights)', 'default' => 4 ),
				array( 'type' => 'text', 'key' => 'badge', 'label' => 'Featured badge', 'default' => 'Featured insight' ),
				array( 'type' => 'text', 'key' => 'read_text', 'label' => 'Featured “read” link text', 'default' => 'Read the insight' ),
				array( 'type' => 'repeater', 'key' => 'items', 'label' => 'Articles (first one is featured)', 'title_field' => 'title', 'fields' => array(
					array( 'type' => 'text', 'key' => 'title', 'label' => 'Title', 'default' => '' ),
					array( 'type' => 'text', 'key' => 'category', 'label' => 'Category line', 'default' => '' ),
					array( 'type' => 'textarea', 'key' => 'excerpt', 'label' => 'Excerpt', 'default' => '' ),
					array( 'type' => 'image', 'key' => 'image', 'label' => 'Image', 'default' => '' ),
					array( 'type' => 'text', 'key' => 'link', 'label' => 'Link', 'default' => '' ),
				), 'default' => array(
					array( 'title' => 'Beyond the Clone Wars: Why It\'s Time to Reimagine the Creative Agency', 'category' => 'Branding • Strategic Narrative', 'excerpt' => 'How visionary market leaders construct enduring brand narrative moats when algorithmic AI content saturates every creative touchpoint.', 'image' => '659284705824048024084208428-1.jpg', 'link' => '/branding/beyond-the-clone-wars-why-its-time-to-reimagine-the-creative-agency/' ),
					array( 'title' => 'AI Doesn\'t Replace Agencies: It Separates the Good Ones from the Average', 'category' => 'Branding & AI • Agency Evolution', 'excerpt' => 'Why artificial intelligence is the ultimate filter separating commoditized output from high-conviction strategic leadership.', 'image' => 'Untitled-design-6.jpg', 'link' => '/branding/ai-doesnt-replace-agencies-it-separates-the-good-ones-from-the-average/' ),
					array( 'title' => 'AI-Powered Digital Transformation: Strategies for Competitive Advantage', 'category' => 'AI & Innovation • Growth Engines', 'excerpt' => 'Deploying intelligent automation, algorithmic media engines, and enterprise data models to capture insurmountable market share.', 'image' => '8500240993188032993214.jpg', 'link' => '/ai/ai-powered-digital-transformation-strategies-for-competitive-advantage/' ),
					array( 'title' => 'Real Work, Real People, Real Learning: My CI360 Internship Story', 'category' => 'Culture & Insights • Agency Life', 'excerpt' => 'An authentic inside look into CI360\'s high-velocity studio culture, 4K production suites, and zero-silos collaboration.', 'image' => '9758025098205-1.jpg', 'link' => '/blog/real-work-real-people-real-learning-my-ci360-internship-story/' ),
				) ),
				array( 'type' => 'section', 'label' => 'Bottom bar' ),
				array( 'type' => 'switch', 'key' => 'show_bottom', 'label' => 'Show bottom bar', 'default' => 'yes' ),
				array( 'type' => 'html', 'key' => 'bottom_label', 'label' => 'Label', 'default' => 'Stay informed.<br>Stay ahead.' ),
				array( 'type' => 'textarea', 'key' => 'bottom_text', 'label' => 'Text', 'default' => 'Curated insights and expert analysis to help you navigate change and lead with confidence.' ),
				array( 'type' => 'text', 'key' => 'cta', 'label' => 'Button text', 'default' => 'Check all insights & articles' ),
				array( 'type' => 'text', 'key' => 'cta_link', 'label' => 'Button link', 'default' => '/blogs/' ),
			),
		),
		'faq' => array(
			'title'    => 'FAQ Accordion',
			'icon'     => 'eicon-accordion',
			'desc'     => 'Questions come from FAQs.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'A LITTLE MORE CLARITY' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'GOOD QUESTIONS. USEFUL ANSWERS.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Before we<br><em>say hello.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro (optional)', 'default' => '' ),
				array( 'type' => 'switch', 'key' => 'reveal', 'label' => 'Animate heading', 'default' => 'yes' ),
				array( 'type' => 'section', 'label' => 'Questions' ),
				array( 'type' => 'term', 'key' => 'group', 'label' => 'FAQ group', 'source' => 'ci_faq_group', 'default' => 'home' ),
				array( 'type' => 'number', 'key' => 'limit', 'label' => 'Number of questions (0 = all)', 'default' => 0 ),
			),
		),
		'compact-cta' => array(
			'title'    => 'Call to Action (compact)',
			'icon'     => 'eicon-call-to-action',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'text', 'label' => 'Heading', 'default' => 'A new chapter starts with a conversation.' ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Button text', 'default' => 'Let\'s talk' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Button link', 'default' => '/contact/' ),
			),
		),
		'page-banner' => array(
			'title'    => 'Page Hero – Banner (image + stats)',
			'icon'     => 'eicon-banner',
			'desc'     => 'Hero for inner pages. In stats and the badge you can use {services}, {projects}, {insights}, {team} or {posts} to show live counts.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Text' ),
				array( 'type' => 'text', 'key' => 'crumb', 'label' => 'Breadcrumb (empty = hide)', 'default' => 'About us' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'ABOUT CI360' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'NAVIGATING CHANGE WITH PURPOSE' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading (page title)', 'default' => 'The brands people<br><em>remember.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'CI360 stands at the forefront of an ever-shifting digital landscape, dedicated to the art of focused attention - always evolving, always looking closer, always building the specific idea that makes a story stick.' ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Button text', 'default' => 'Meet our founders' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Button link', 'default' => '/founders/' ),
				array( 'type' => 'text', 'key' => 'secondary', 'label' => 'Second link text', 'default' => 'Explore our work' ),
				array( 'type' => 'text', 'key' => 'secondary_link', 'label' => 'Second link', 'default' => '/work/' ),
				array( 'type' => 'section', 'label' => 'Images' ),
				array( 'type' => 'image', 'key' => 'image', 'label' => 'Main image', 'default' => 'studio.webp' ),
				array( 'type' => 'image', 'key' => 'image_2', 'label' => 'Small image (optional)', 'default' => 'studio-detail.webp' ),
				array( 'type' => 'text', 'key' => 'card_value', 'label' => 'Badge number', 'default' => '2017' ),
				array( 'type' => 'text', 'key' => 'card_label', 'label' => 'Badge text', 'default' => 'Connecting stories since' ),
				array( 'type' => 'section', 'label' => 'Stats' ),
				array( 'type' => 'repeater', 'key' => 'stats', 'label' => 'Stats (leave empty to hide)', 'title_field' => 'label', 'fields' => array(
					array( 'type' => 'text', 'key' => 'value', 'label' => 'Number', 'default' => '' ),
					array( 'type' => 'text', 'key' => 'label', 'label' => 'Label', 'default' => '' ),
				), 'default' => array(
					array( 'value' => '{team}', 'label' => 'Minds on the team' ),
					array( 'value' => '3', 'label' => 'Locations, one team' ),
					array( 'value' => '{projects}', 'label' => 'Brands in the collection' ),
				) ),
			),
		),
		'blog-archive' => array(
			'title'    => 'Blog – Archive (filters + search)',
			'icon'     => 'eicon-archive-posts',
			'desc'     => 'All blog posts with category filter pills, instant search and cards. Posts in “case study” categories are left out.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Posts' ),
				array( 'type' => 'text', 'key' => 'anchor', 'label' => 'Section ID', 'default' => 'posts' ),
				array( 'type' => 'number', 'key' => 'count', 'label' => 'Maximum posts', 'default' => 60 ),
				array( 'type' => 'text', 'key' => 'exclude', 'label' => 'Leave out categories containing (comma separated)', 'default' => 'case study, case studies, case-study, case-studies' ),
				array( 'type' => 'switch', 'key' => 'fallback', 'label' => 'No posts yet? Show CI360 Insights instead', 'default' => 'yes' ),
				array( 'type' => 'section', 'label' => 'Text' ),
				array( 'type' => 'text', 'key' => 'all_label', 'label' => '“All” filter', 'default' => 'All insights' ),
				array( 'type' => 'text', 'key' => 'search', 'label' => 'Search placeholder', 'default' => 'Search essays & topics' ),
				array( 'type' => 'text', 'key' => 'count_label', 'label' => 'Count label', 'default' => 'articles in view' ),
				array( 'type' => 'text', 'key' => 'read_more', 'label' => 'Card link text', 'default' => 'Read more' ),
				array( 'type' => 'text', 'key' => 'default_author', 'label' => 'Author when none', 'default' => 'CI360 Desk' ),
				array( 'type' => 'html', 'key' => 'empty_heading', 'label' => 'No results heading', 'default' => 'Nothing on that<br><em>just yet.</em>' ),
				array( 'type' => 'text', 'key' => 'empty_text', 'label' => 'No results text', 'default' => 'No articles match your search. Try another topic or show everything.' ),
				array( 'type' => 'text', 'key' => 'empty_button', 'label' => 'No results button', 'default' => 'Show all articles' ),
			),
		),
		'blog-grid' => array(
			'title'    => 'Blog – Posts Grid',
			'icon'     => 'eicon-posts-grid',
			'desc'     => 'Lists WordPress blog posts with pagination.',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'anchor', 'label' => 'Section ID', 'default' => 'posts' ),
				array( 'type' => 'number', 'key' => 'per_page', 'label' => 'Posts per page', 'default' => 9 ),
				array( 'type' => 'term', 'key' => 'category', 'label' => 'Category (empty = all)', 'source' => 'category', 'default' => '' ),
				array( 'type' => 'switch', 'key' => 'fallback', 'label' => 'No posts yet? Show CI360 Insights instead', 'default' => 'yes' ),
				array( 'type' => 'text', 'key' => 'empty', 'label' => 'Text when there is nothing to show', 'default' => 'New articles are on their way.' ),
			),
		),
		'page-hero' => array(
			'title'    => 'Page Hero',
			'icon'     => 'eicon-header',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'crumb', 'label' => 'Breadcrumb', 'default' => 'About us' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'ABOUT CI360' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'NAVIGATING CHANGE WITH PURPOSE' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'The brands people<br><em>remember.</em>' ),
				array( 'type' => 'text', 'key' => 'intro_short', 'label' => 'Intro (short)', 'default' => 'Because great stories endure.' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'CI360 stands at the forefront of an ever-shifting digital landscape, dedicated to the art of focused attention. Each strand of content and every pixel of design reflects our belief in the transformative power of digital. Our team remains a community of learners and innovators - always evolving, always looking closer, always building the specific idea that makes a story stick.' ),
				array( 'type' => 'section', 'label' => 'Wide image' ),
				array( 'type' => 'switch', 'key' => 'show_image', 'label' => 'Show wide image', 'default' => 'yes' ),
				array( 'type' => 'image', 'key' => 'image', 'label' => 'Image', 'default' => 'studio.webp' ),
				array( 'type' => 'text', 'key' => 'image_note', 'label' => 'Image note', 'default' => 'A COMMUNITY OF LEARNERS & INNOVATORS' ),
				array( 'type' => 'html', 'key' => 'image_type', 'label' => 'Image overlay type', 'default' => 'Always<br>looking closer.' ),
			),
		),
		'about-compass' => array(
			'title'    => 'About – Vision, Mission & Values',
			'icon'     => 'eicon-info-box',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'OUR COMPASS' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'VISION. MISSION. VALUES.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Purpose in<br><em>every direction.</em>' ),
				array( 'type' => 'section', 'label' => 'Cards' ),
				array( 'type' => 'text', 'key' => 'vision_title', 'label' => 'Vision title', 'default' => 'A broader perspective.' ),
				array( 'type' => 'textarea', 'key' => 'vision', 'label' => 'Vision', 'default' => 'To be a globally trusted marketing partner, where creativity, technology, and innovation redefine brand communication.' ),
				array( 'type' => 'text', 'key' => 'mission_title', 'label' => 'Mission title', 'default' => 'Ideas into impact.' ),
				array( 'type' => 'textarea', 'key' => 'mission', 'label' => 'Mission', 'default' => 'To empower brands through strategic storytelling, creativity, and technology that drive meaningful engagement and measurable growth.' ),
				array( 'type' => 'text', 'key' => 'values_title', 'label' => 'Values title', 'default' => 'What keeps us true.' ),
				array( 'type' => 'repeater', 'key' => 'values', 'label' => 'Values', 'title_field' => 'value', 'fields' => array( array( 'type' => 'text', 'key' => 'value', 'label' => 'Value', 'default' => '' ) ), 'default' => array( array( 'value' => 'Strategic Storytelling' ), array( 'value' => 'Innovation & Excellence' ), array( 'value' => 'Integrity & Transparency' ), array( 'value' => 'Client-Centric Approach' ), array( 'value' => 'Collaboration & Growth' ) ) ),
			),
		),
		'about-belief' => array(
			'title'    => 'About – The Way We Think',
			'icon'     => 'eicon-blockquote',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'THE WAY WE THINK' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'A SINGLE INTEGRATED DIRECTION' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'We turn ideas<br>into <em>impactful<br>solutions.</em>' ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Button', 'default' => 'Meet our founders' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Button link', 'default' => '/founders/' ),
				array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Text (first paragraph is large; blank line between paragraphs)', 'default' => 'CI360 stands at the forefront of the digital revolution, embodying the spirited curiosity of the current times. In this era where digital landscapes shift with the wind, our agency emerges as a beacon of integrated marketing services, dedicated to the art of focused attention.

At CI360, the mission is to seamlessly integrate cutting-edge technologies like AI, VR, AR, and the Metaverse with traditional forms of communication, crafting engaging narratives that revolutionize digital marketing.

Navigating the digital realm with a splash of creativity and a dash of strategic magic. CI360 believes in the transformative power of digital and pledges to remain learners and innovators, forever evolving, while understanding the nuance and specificity that make stories and campaigns stick.' ),
			),
		),
		'about-journey' => array(
			'title'    => 'About – Timeline',
			'icon'     => 'eicon-time-line',
			'desc'     => 'Interactive CI360 journey with year navigation, imagery, tags and auto-slide.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Built one <em>meaningful</em><br>business problem at a time.' ),
				array( 'type' => 'color', 'key' => 'heading_color', 'label' => 'Heading color', 'default' => '#ffffff' ),
				array( 'type' => 'color', 'key' => 'accent_color', 'label' => 'Accent text color', 'default' => '#22d3ee' ),
				array( 'type' => 'color', 'key' => 'card_title_color', 'label' => 'Card title color', 'default' => '#ffffff' ),
				array( 'type' => 'select', 'key' => 'font_weight', 'label' => 'Heading font weight', 'options' => array(
					'300' => 'Light (300)',
					'400' => 'Regular (400)',
					'500' => 'Medium (500)',
					'600' => 'SemiBold (600)',
					'700' => 'Bold (700)',
					'800' => 'ExtraBold (800)',
				), 'default' => '600' ),
				array( 'type' => 'section', 'label' => 'Milestones' ),
				array( 'type' => 'repeater', 'key' => 'timeline', 'label' => 'Timeline', 'title_field' => 'year', 'fields' => array(
					array( 'type' => 'text', 'key' => 'year', 'label' => 'Year', 'default' => '' ),
					array( 'type' => 'html', 'key' => 'title', 'label' => 'Title', 'default' => '' ),
					array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Description', 'default' => '' ),
					array( 'type' => 'text', 'key' => 'tags', 'label' => 'Tags (separate with |)', 'default' => '' ),
					array( 'type' => 'image', 'key' => 'image', 'label' => 'Image', 'default' => '' ),
				), 'default' => array(
					array( 'year' => '2017', 'title' => 'Founded by a veteran of <br>18 years in core <br>marketing functions.', 'text' => 'We started by getting closer to businesses, their audiences, and the challenges that truly mattered.', 'tags' => 'Strategy|Research|Clarity', 'image' => 'studio.webp' ),
					array( 'year' => '2018', 'title' => 'Launched digital <br>marketing services <br>in the US.', 'text' => 'Launched digital marketing services in the US, expanding our reach into new markets.', 'tags' => 'Digital|Expansion|US Market', 'image' => 'studio-detail.webp' ),
					array( 'year' => '2019', 'title' => 'Ideas Became <br>Connected Brand <br>Experiences.', 'text' => 'Our canvas widened as we began shaping brands across multiple communication touchpoints.', 'tags' => 'Brand|Content|Digital', 'image' => 'story.webp' ),
					array( 'year' => '2020', 'title' => 'Growing fast in Ahmedabad, Delhi, Mumbai & the US — focused on SMEs.', 'text' => 'New realities pushed us to rethink faster, respond smarter, and help brands navigate uncertainty.', 'tags' => 'Agility|Focus|Momentum', 'image' => 'event.webp' ),
					array( 'year' => '2021', 'title' => 'Expanded US operations in digital marketing and custom software development.', 'text' => 'Ideas gained greater scale and precision as new tools reshaped how we brought them to life.', 'tags' => 'Technology|Automation|Performance', 'image' => 'connectivity.webp' ),
					array( 'year' => '2023', 'title' => 'Expanded horizons — introduced business consultancy to the portfolio.', 'text' => 'A single narrative approach began guiding every interaction, from the first idea to the final customer experience.', 'tags' => 'Consulting|Storytelling|Delivery', 'image' => 'Asset-2365.jpg' ),
					array( 'year' => '2024', 'title' => 'Pioneering AI, <br>forging a path toward <br>transformative growth.', 'text' => 'Pioneering AI, forging a path toward transformative growth across every service line.', 'tags' => 'AI|Innovation|Growth', 'image' => 'ChatGPT-Image-Sep-10-2026-12_52_16-PM.jpg' ),
					array( 'year' => '2025', 'title' => 'Expansion and hiring <br>of talent across <br>segments.', 'text' => 'Expansion and hiring of talent across segments, strengthening our teams and capabilities nationwide.', 'tags' => 'Expansion|Talent|Scale', 'image' => 'team/122A0148.webp' ),
					array( 'year' => 'NOW', 'title' => 'One Integrated Partner<br> for Meaningful<br> Growth.', 'text' => 'We now solve business challenges through connected thinking that turns opportunities into measurable outcomes.', 'tags' => 'Intelligence|Judgement|Impact', 'image' => 'ChatGPT-Image-Sep-10-2026-01_07_52-PM-e1789027835491.png' ),
				) ),
			),
		),
		'about-team' => array(
			'title'    => 'Team – Meet the Minds',
			'icon'     => 'eicon-person',
			'desc'     => 'Members come from Team (photo = Member photo field).',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Heading' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'THE PEOPLE' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'DIFFERENT MINDS. SHARED PURPOSE.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'The thinking<br><em>behind the work.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'A multidisciplinary team connecting strategy, creative, technology and delivery.' ),
				array( 'type' => 'text', 'key' => 'anchor', 'label' => 'Section ID', 'default' => 'team' ),
				array( 'type' => 'section', 'label' => 'Members' ),
				array( 'type' => 'number', 'key' => 'count', 'label' => 'Number of members (0 = all)', 'default' => 0 ),
			),
		),
		'about-industries' => array(
			'title'    => 'About – Industries',
			'icon'     => 'eicon-tags',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'OUR WORLD' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'ACROSS INDUSTRIES. ACROSS MARKETS.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Many worlds.<br><em>One connected team.</em>' ),
				array( 'type' => 'repeater', 'key' => 'industries', 'label' => 'Industries', 'title_field' => 'name', 'fields' => array( array( 'type' => 'text', 'key' => 'name', 'label' => 'Industry', 'default' => '' ) ), 'default' => array( array( 'name' => 'Satellite Communications' ), array( 'name' => 'Health & Wellness' ), array( 'name' => 'FMCG & Beverages' ), array( 'name' => 'Fashion' ), array( 'name' => 'Beauty' ), array( 'name' => 'Real Estate' ), array( 'name' => 'Spirituality' ), array( 'name' => 'NBFC & Financial Services' ), array( 'name' => 'Knowledge Centres & NGOs' ), array( 'name' => 'Education' ), array( 'name' => 'Government' ), array( 'name' => 'Consumer Durables' ), array( 'name' => 'Hospitality' ), array( 'name' => 'Media & OOH' ), array( 'name' => 'FPO' ) ) ),
			),
		),
		'founders-profiles' => array(
			'title'    => 'Founders – Profiles',
			'icon'     => 'eicon-user-circle-o',
			'desc'     => 'Profiles come from Team members marked “Is a founder”.',
			'controls' => array(
				array( 'type' => 'image', 'key' => 'fallback_image', 'label' => 'Portrait fallback image', 'default' => 'studio.webp' ),
			),
		),
		'founders-belief' => array(
			'title'    => 'Founders – Shared Belief',
			'icon'     => 'eicon-blockquote',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'BUILT ON A SHARED BELIEF' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'GREAT MARKETING BEGINS WITH LISTENING' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'A story rooted<br>in <em>purpose.</em>' ),
				array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Text (blank line between paragraphs)', 'default' => 'CI360 was founded on a simple belief that great marketing begins long before the first campaign. It begins with listening, understanding the business, the people behind it, and the challenges they face. Strategic storytelling becomes the foundation for meaningful connections between brands and audiences.

The mission is to help brands grow by combining creativity, technology, and strategy into integrated marketing solutions. Solutions span branding, websites, social media, performance marketing, SEO, GEO, local search optimization, Google Business Profile management, content strategy, and emerging technologies.

While marketing continues to evolve through AI, automation, and immersive digital experiences, one principle remains constant: brands that communicate with purpose are the ones people remember.' ),
			),
		),
		'founders-studio' => array(
			'title'    => 'Founders – Studio',
			'icon'     => 'eicon-image-box',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'image', 'key' => 'image', 'label' => 'Image', 'default' => 'studio.webp' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Studio heading', 'default' => 'Good ideas<br>need <em>good company.</em>' ),
				array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Studio text', 'default' => 'Our team remains a community of learners and innovators - always evolving, always looking closer, always building the specific idea that makes a story stick.' ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Studio button', 'default' => 'Meet the whole team' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Studio button link', 'default' => '/about/#team' ),
			),
		),
		'services-hero' => array(
			'title'    => 'Services – Hero',
			'icon'     => 'eicon-header',
			'desc'     => 'Editable Services hero. Choose the layout, visual source, copy and CTA directly in Elementor.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Layout' ),
				array( 'type' => 'select', 'key' => 'hero_style', 'label' => 'Hero style', 'default' => 'editorial', 'options' => array( 'editorial' => 'Editorial split (new)', 'panel' => 'Blue panel', 'minimal' => 'Minimal text' ) ),
				array( 'type' => 'image', 'key' => 'hero_background', 'label' => 'Optional background image', 'default' => '' ),
				array( 'type' => 'switch', 'key' => 'show_visual', 'label' => 'Show service visual', 'default' => 'yes' ),
				array( 'type' => 'switch', 'key' => 'show_badge', 'label' => 'Show capability badge', 'default' => 'yes' ),
				array( 'type' => 'section', 'label' => 'Content' ),
				array( 'type' => 'text', 'key' => 'crumb', 'label' => 'Breadcrumb', 'default' => 'Services' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'OUR CAPABILITIES' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'STRATEGY THROUGH TO EXECUTION' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'One partner.<br><em>Every possibility.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'From strategic storytelling and brand building to digital marketing, AI search visibility, content, technology and performance. Every capability, together around meaningful, measurable growth.' ),
				array( 'type' => 'text', 'key' => 'button', 'label' => 'Button', 'default' => 'Find your next move' ),
				array( 'type' => 'text', 'key' => 'button_link', 'label' => 'Button link', 'default' => '/contact/' ),
				array( 'type' => 'post', 'key' => 'service', 'label' => 'Hero visual (service)', 'source' => 'ci_service', 'default' => 'websites-digital-experiences' ),
				array( 'type' => 'html', 'key' => 'badge', 'label' => 'Badge small text', 'default' => 'CONNECTED<br>CAPABILITIES' ),
			),
		),
		'services-grid' => array(
			'title'    => 'Services – Card Grid',
			'icon'     => 'eicon-gallery-grid',
			'desc'     => 'Cards come from Services.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Layout' ),
				array( 'type' => 'text', 'key' => 'anchor', 'label' => 'Section ID', 'default' => 'capabilities' ),
				array( 'type' => 'select', 'key' => 'layout', 'label' => 'Card layout', 'default' => 'editorial', 'options' => array( 'editorial' => 'Editorial cards (new)', 'classic' => 'Classic 3-column cards', 'compact' => 'Compact list' ) ),
				array( 'type' => 'select', 'key' => 'columns', 'label' => 'Editorial columns', 'default' => '2', 'options' => array( '2' => '2 columns', '3' => '3 columns' ) ),
				array( 'type' => 'switch', 'key' => 'show_summary', 'label' => 'Show service summary', 'default' => 'yes' ),
				array( 'type' => 'switch', 'key' => 'show_tags', 'label' => 'Show service tags', 'default' => 'yes' ),
				array( 'type' => 'text', 'key' => 'button_label', 'label' => 'Card link text', 'default' => 'Explore service' ),
				array( 'type' => 'section', 'label' => 'Content source' ),
				array( 'type' => 'term', 'key' => 'group', 'label' => 'Service group (empty = all)', 'source' => 'ci_service_group', 'default' => '' ),
				array( 'type' => 'number', 'key' => 'count', 'label' => 'Number of services (0 = all)', 'default' => 0 ),
				array( 'type' => 'section', 'label' => 'Optional section heading' ),
				array( 'type' => 'switch', 'key' => 'show_heading', 'label' => 'Show heading above cards', 'default' => '' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'WHAT WE DO' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'CONNECTED CAPABILITIES' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Capabilities built to <em>work together.</em>' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'Choose a specialist capability or connect several disciplines around one business goal.' ),
			),
		),
		'work-hero' => array(
			'title'    => 'Work – Hero',
			'icon'     => 'eicon-header',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'crumb', 'label' => 'Breadcrumb', 'default' => 'Work' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'THE PORTFOLIO' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'OUR WORK. YOUR NEXT POSSIBILITY.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Different worlds.<br><em>Distinctive work.</em>' ),
				array( 'type' => 'html', 'key' => 'circle', 'label' => 'Circle text', 'default' => 'BRANDS IN<br>THE COLLECTION' ),
				array( 'type' => 'text', 'key' => 'intro_short', 'label' => 'Intro (short)', 'default' => 'Creativity meets strategy.' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'Dive into CI360\'s digital marketing solutions, where creativity meets strategy to drive brand growth. A collection of client brands, creative galleries and sector perspectives.' ),
			),
		),
		'work-portfolio' => array(
			'title'    => 'Work – Portfolio Grid & Filters',
			'icon'     => 'eicon-filter',
			'desc'     => 'Projects come from Projects; filter pills are categories marked “Show as filter”.',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'anchor', 'label' => 'Section ID', 'default' => 'portfolio' ),
				array( 'type' => 'switch', 'key' => 'space_top', 'label' => 'Space above the filters', 'default' => 'yes' ),
				array( 'type' => 'text', 'key' => 'all', 'label' => 'Filter “All” label', 'default' => 'All' ),
				array( 'type' => 'text', 'key' => 'search', 'label' => 'Search placeholder', 'default' => 'Find a brand' ),
				array( 'type' => 'text', 'key' => 'count_label', 'label' => 'Count label', 'default' => 'projects in view' ),
				array( 'type' => 'html', 'key' => 'empty_heading', 'label' => 'No results heading', 'default' => 'A different<br>search, perhaps?' ),
				array( 'type' => 'text', 'key' => 'empty_text', 'label' => 'No results text', 'default' => 'Try another brand name or explore the full collection.' ),
				array( 'type' => 'text', 'key' => 'empty_button', 'label' => 'No results button', 'default' => 'Show all projects' ),
				array( 'type' => 'textarea', 'key' => 'note', 'label' => 'Portfolio note', 'default' => 'Creative galleries use supplied imagery. Portfolio perspectives use clearly labelled editorial sector imagery and do not assert project results.' ),
			),
		),
		'insights-list' => array(
			'title'    => 'Insights – Editorial Archive',
			'icon'     => 'eicon-posts-grid',
			'desc'     => 'Dark editorial Insights archive with spotlight story, topic filters and instant search.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Hero' ),
				array( 'type' => 'text', 'key' => 'anchor', 'label' => 'Section ID', 'default' => 'articles' ),
				array( 'type' => 'select', 'key' => 'hero_style', 'label' => 'Hero layout', 'default' => 'cinematic', 'options' => array( 'cinematic' => 'Cinematic feature (new)', 'split' => 'Split card', 'minimal' => 'Minimal text' ) ),
				array( 'type' => 'switch', 'key' => 'show_spotlight', 'label' => 'Show featured article', 'default' => 'yes' ),
				array( 'type' => 'image', 'key' => 'hero_background', 'label' => 'Optional hero background image', 'default' => '' ),
				array( 'type' => 'text', 'key' => 'badge', 'label' => 'Badge', 'default' => 'Strategic Intelligence & Thought Leadership' ),
				array( 'type' => 'text', 'key' => 'heading_1', 'label' => 'Heading line 1', 'default' => 'Insights &' ),
				array( 'type' => 'text', 'key' => 'heading_2', 'label' => 'Heading accent', 'default' => 'Perspectives.' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'Marketing never stops evolving, and neither does our thinking. Explore CI360 perspectives on strategic storytelling, digital marketing trends, AI in marketing, SEO, AEO, GEO, performance marketing, brand strategy, content marketing, podcasting, and changing consumer behaviour.' ),
				array( 'type' => 'text', 'key' => 'cta', 'label' => 'CTA text', 'default' => "Let's Connect" ),
				array( 'type' => 'text', 'key' => 'cta_link', 'label' => 'CTA link', 'default' => '/contact/' ),
				array( 'type' => 'section', 'label' => 'Archive' ),
				array( 'type' => 'text', 'key' => 'all_label', 'label' => 'All filter', 'default' => 'All Insights' ),
				array( 'type' => 'text', 'key' => 'search', 'label' => 'Search placeholder', 'default' => 'Search essays & topics...' ),
				array( 'type' => 'text', 'key' => 'read_more', 'label' => 'Read button', 'default' => 'Read More' ),
				array( 'type' => 'text', 'key' => 'default_author', 'label' => 'Default author', 'default' => 'CI360 Desk' ),
				array( 'type' => 'html', 'key' => 'empty_heading', 'label' => 'No results heading', 'default' => 'No insights found.' ),
				array( 'type' => 'text', 'key' => 'empty_text', 'label' => 'No results text', 'default' => 'Try another topic or clear the search.' ),
				array( 'type' => 'text', 'key' => 'empty_button', 'label' => 'Reset button', 'default' => 'Show all insights' ),
				array( 'type' => 'textarea', 'key' => 'note', 'label' => 'Note under grid', 'default' => 'Studio notes: newly written editorial drafts developed from the themes in the supplied website content. Review before publication.' ),
			),
		),
		'topics' => array(
			'title'    => 'Insights – Topics',
			'icon'     => 'eicon-tags',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'WHAT WE THINK ABOUT' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'A CURIOUS MIND DOES NOT STAND STILL' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'More ways<br>to <em>look closer.</em>' ),
				array( 'type' => 'repeater', 'key' => 'topics', 'label' => 'Topics (link to contact form)', 'title_field' => 'topic', 'fields' => array( array( 'type' => 'text', 'key' => 'topic', 'label' => 'Topic', 'default' => '' ) ), 'default' => array( array( 'topic' => 'Strategic storytelling' ), array( 'topic' => 'Digital marketing' ), array( 'topic' => 'AI in marketing' ), array( 'topic' => 'SEO, AEO & GEO' ), array( 'topic' => 'Performance marketing' ), array( 'topic' => 'Brand strategy' ), array( 'topic' => 'Content marketing' ), array( 'topic' => 'Podcasting' ), array( 'topic' => 'Consumer behaviour' ) ) ),
				array( 'type' => 'text', 'key' => 'link', 'label' => 'Link', 'default' => '/contact/' ),
			),
		),
		'contact-main' => array(
			'title'    => 'Contact – Details & Form',
			'icon'     => 'eicon-form-horizontal',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Intro' ),
				array( 'type' => 'switch', 'key' => 'show_crumb', 'label' => 'Show breadcrumb', 'default' => 'yes' ),
				array( 'type' => 'select', 'key' => 'heading_tag', 'label' => 'Heading level', 'default' => 'h1', 'options' => array( 'h1' => 'H1 (page title)', 'h2' => 'H2 (when a Page Hero is above)' ) ),
				array( 'type' => 'text', 'key' => 'crumb', 'label' => 'Breadcrumb', 'default' => 'Contact' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'YOUR NEXT CHAPTER' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'STARTS HERE' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Let&apos;s make<br><em>something<br>matter.</em>' ),
				array( 'type' => 'textarea', 'key' => 'lead', 'label' => 'Lead', 'default' => 'Every great story starts with a conversation. We&apos;d love to hear from you.' ),
				array( 'type' => 'repeater', 'key' => 'blocks', 'label' => 'Contact details', 'title_field' => 'label', 'fields' => array( array( 'type' => 'text', 'key' => 'label', 'label' => 'Label', 'default' => '' ), array( 'type' => 'text', 'key' => 'email', 'label' => 'Email', 'default' => '' ), array( 'type' => 'text', 'key' => 'phone', 'label' => 'Phone', 'default' => '' ) ), 'default' => array( array( 'label' => 'INDIA', 'email' => 'pramit.ghosh@ci360degrees.com', 'phone' => '+91 97118 09099' ), array( 'label' => 'UNITED STATES', 'email' => 'bhumi@ci360degrees.com', 'phone' => '+1 (864) 990-5354' ) ) ),
				array( 'type' => 'image', 'key' => 'image', 'label' => 'Photo', 'default' => 'studio.webp' ),
				array( 'type' => 'text', 'key' => 'image_label', 'label' => 'Photo label', 'default' => 'ONE CONNECTED TEAM.' ),
				array( 'type' => 'text', 'key' => 'confidential', 'label' => 'Confidential line (use | between items)', 'default' => 'Let&apos;s connect | 100% confidential | We sign NDA' ),
				array( 'type' => 'section', 'label' => 'Form' ),
				array( 'type' => 'text', 'key' => 'form_label', 'label' => 'Form label', 'default' => 'LET\'S CREATE SOMETHING EXCEPTIONAL.' ),
				array( 'type' => 'html', 'key' => 'form_heading', 'label' => 'Form heading', 'default' => 'Tell us what<br>you&apos;re <em>thinking.</em>' ),
				array( 'type' => 'textarea', 'key' => 'form_intro', 'label' => 'Form intro', 'default' => 'Share your goal, your challenge and where you are in the process. A rough brief is fine.' ),
				array( 'type' => 'text', 'key' => 'extra_1', 'label' => 'Extra service option 1', 'default' => 'An integrated marketing partnership' ),
				array( 'type' => 'text', 'key' => 'extra_2', 'label' => 'Extra service option 2', 'default' => 'Let\'s work it out together' ),
				array( 'type' => 'html', 'key' => 'consent', 'label' => 'Consent text', 'default' => 'I agree that CI360 may use my details to respond to this enquiry. I have read the <a href="/privacy-policy/">Privacy Policy</a> and <a href="/terms-and-conditions/">Terms &amp; Conditions</a>.' ),
			),
		),
		'locations' => array(
			'title'    => 'Contact – Office Locations',
			'icon'     => 'eicon-map-pin',
			'desc'     => 'Offices come from CI360 Settings › Offices.',
			'controls' => array(
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'HERE. THERE. TOGETHER.' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'THREE LOCATIONS. ONE CONNECTED TEAM.' ),
				array( 'type' => 'html', 'key' => 'heading', 'label' => 'Heading', 'default' => 'Local understanding.<br><em>Connected perspectives.</em>' ),
			),
		),
		'legal' => array(
			'title'    => 'Legal Page Content',
			'icon'     => 'eicon-document-file',
			'desc'     => '',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Intro' ),
				array( 'type' => 'text', 'key' => 'title', 'label' => 'Title (empty = page title)', 'default' => '' ),
				array( 'type' => 'text', 'key' => 'label_1', 'label' => 'Label (left)', 'default' => 'THE DETAILS' ),
				array( 'type' => 'text', 'key' => 'label_2', 'label' => 'Label (right)', 'default' => 'DRAFT / REVIEW BEFORE PUBLICATION' ),
				array( 'type' => 'textarea', 'key' => 'intro', 'label' => 'Intro', 'default' => 'A clear view of how this website handles your information.' ),
				array( 'type' => 'html', 'key' => 'art', 'label' => 'Side art text', 'default' => 'Clarity<br>comes first.' ),
				array( 'type' => 'textarea', 'key' => 'aside', 'label' => 'Side note', 'default' => 'Draft operational copy. Owner and legal review required before launch.' ),
				array( 'type' => 'section', 'label' => 'Sections' ),
				array( 'type' => 'repeater', 'key' => 'sections', 'label' => 'Sections', 'title_field' => 'title', 'fields' => array( array( 'type' => 'text', 'key' => 'title', 'label' => 'Title', 'default' => '' ), array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Text', 'default' => '' ) ), 'default' => array( array( 'title' => 'About this draft', 'text' => 'This is a website-specific policy draft for CI360 review before launch. It describes the supplied website implementation, not a verified audit of CI360\'s wider systems. The final website owner should confirm the operational details and obtain appropriate legal review before publishing.' ), array( 'title' => 'Information you choose to provide', 'text' => 'The enquiry form asks for your name, email, phone number, company, country, service of interest and message. Required fields are marked. Please provide only the information needed to discuss your project, and do not submit passwords, payment credentials or sensitive personal information.' ), array( 'title' => 'What happens when you make an enquiry', 'text' => 'In the default email-draft mode, form details remain in the current page until you choose to open an email draft. Your email application then handles the message, and it is sent only when you send it there. The website does not claim to have received that message before it is sent. If the site owner enables server delivery, this policy must identify the relevant email or CRM providers and their processing arrangements.' ), array( 'title' => 'Local preferences and external services', 'text' => 'The website may store your motion preference in your browser\'s local storage so that it can remember whether animations are enabled. This build does not include advertising pixels or third-party analytics scripts. Poppins is requested from Google Fonts, and the founders page can request portrait images from CI360\'s existing website; those requests are handled by the respective providers and may include normal connection information. The host may also maintain access and security logs.' ), array( 'title' => 'Use, access and retention', 'text' => 'Enquiry information is intended to help CI360 understand and respond to your request. The organisation should define and publish its actual access controls, service providers, retention periods and deletion procedure before enabling server-side form delivery. This draft does not invent a retention period or promise a technical control that has not been verified.' ), array( 'title' => 'Questions or requests', 'text' => 'For questions about an enquiry or this draft, contact pramit.ghosh@ci360degrees.com. Include enough context to identify your request, but do not include unnecessary sensitive information. Any formal rights request should be handled under the law and processes applicable to the organisation and the request.' ), array( 'title' => 'Updates', 'text' => 'The owner should review this policy whenever hosting, analytics, forms, advertising, integrations or data handling changes. Publish an accurate effective date when the final version is approved.' ) ) ),
			),
		),
		'service-detail' => array(
			'title'    => 'Service – Full Detail (current service)',
			'icon'     => 'eicon-single-post',
			'desc'     => 'For single-service templates. Uses the current service unless one is chosen.',
			'controls' => array(
				array( 'type' => 'post', 'key' => 'service', 'label' => 'Service (empty = current)', 'source' => 'ci_service', 'default' => '' ),
			),
		),
		'project-detail' => array(
			'title'    => 'Project – Full Detail (current project)',
			'icon'     => 'eicon-single-post',
			'desc'     => 'For single-project templates.',
			'controls' => array(
				array( 'type' => 'post', 'key' => 'project', 'label' => 'Project (empty = current)', 'source' => 'ci_project', 'default' => '' ),
			),
		),
		'insight-detail' => array(
			'title'    => 'Insight – Full Article (current insight)',
			'icon'     => 'eicon-single-post',
			'desc'     => 'For single-insight templates.',
			'controls' => array(
				array( 'type' => 'post', 'key' => 'insight', 'label' => 'Insight (empty = current)', 'source' => 'ci_insight', 'default' => '' ),
			),
		),
		'site-header' => array(
			'title'    => 'Site Header',
			'icon'     => 'eicon-header',
			'desc'     => 'Header, menu and overlay. Uses CI360 Settings and Appearance › Menus.',
			'controls' => array(
			),
		),
		'site-footer' => array(
			'title'    => 'Site Footer',
			'icon'     => 'eicon-footer',
			'desc'     => 'Footer. Uses CI360 Settings and Appearance › Menus.',
			'controls' => array(
			),
		),
		'impact-brand' => array(
			'title'    => 'Impact and Brand Channels',
			'icon'     => 'eicon-rating',
			'desc'     => 'Displays Brand Channels social icons bar and customizable 3-column Impact cards grid.',
			'controls' => array(
				array( 'type' => 'section', 'label' => 'Brand Channels' ),
				array( 'type' => 'text', 'key' => 'channels_title', 'label' => 'Brand Channels Title', 'default' => 'Brand Channels:' ),
				array(
					'type'        => 'repeater',
					'key'         => 'channels',
					'label'       => 'Social Channels',
					'title_field' => 'platform',
					'fields'      => array(
						array( 'type' => 'text', 'key' => 'platform', 'label' => 'Platform (facebook, twitter, linkedin, instagram, wordpress)', 'default' => 'facebook' ),
						array( 'type' => 'text', 'key' => 'url', 'label' => 'Link URL', 'default' => '#' ),
					),
					'default'     => array(
						array( 'platform' => 'facebook', 'url' => '#' ),
						array( 'platform' => 'twitter', 'url' => '#' ),
						array( 'platform' => 'linkedin', 'url' => '#' ),
						array( 'platform' => 'instagram', 'url' => '#' ),
						array( 'platform' => 'wordpress', 'url' => '#' ),
					),
				),
				array( 'type' => 'section', 'label' => 'The Impact' ),
				array( 'type' => 'text', 'key' => 'impact_title', 'label' => 'Impact Box Title', 'default' => 'The Impact' ),
				array(
					'type'        => 'repeater',
					'key'         => 'impact_cards',
					'label'       => 'Impact Cards',
					'title_field' => 'text',
					'fields'      => array(
						array( 'type' => 'textarea', 'key' => 'text', 'label' => 'Card Text', 'default' => '' ),
					),
					'default'     => array(
						array( 'text' => 'Created a completely new logo, brand identity, and brand book.' ),
						array( 'text' => 'Designed and developed the website around Station Satcom\'s evolving technology portfolio.' ),
						array( 'text' => 'Built and continue to manage its social media and always-on content ecosystem.' ),
					),
				),
			),
		),
	);
	// Client logos default: every logo bundled with the theme.
	$defs['brand-strip']['controls'][1]['default'] = ci_default_logos();
	return $defs;
}
